"""add_notification_preferences

Revision ID: 7e232784a7b2
Revises: 4e071f196323
Create Date: 2026-05-24 02:44:09.372607

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7e232784a7b2'
down_revision: Union[str, None] = '4e071f196323'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification_preferences',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('tenant_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('filter_not_following', sa.Boolean(), nullable=False),
    sa.Column('filter_not_followed_by', sa.Boolean(), nullable=False),
    sa.Column('filter_new_accounts', sa.Boolean(), nullable=False),
    sa.Column('highlight_unread', sa.Boolean(), nullable=False),
    sa.Column('display_all_categories', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notification_preferences_tenant_id'), 'notification_preferences', ['tenant_id'], unique=False)
    op.create_index('ix_notification_preferences_tenant_user', 'notification_preferences', ['tenant_id', 'user_id'], unique=False)
    op.create_index(op.f('ix_notification_preferences_user_id'), 'notification_preferences', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_notification_preferences_user_id'), table_name='notification_preferences')
    op.drop_index('ix_notification_preferences_tenant_user', table_name='notification_preferences')
    op.drop_index(op.f('ix_notification_preferences_tenant_id'), table_name='notification_preferences')
    op.drop_table('notification_preferences')
    # ### end Alembic commands ###
